### ISSUE TITLE
mac:instrument within mac:platform

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/metadata-xml#35]
metadata schema indicates instrument should be nested within platform (as we have it on [L887](https://github.com/cioos-siooc/metadata-xml/blob/192130b74ae75c466edf74166a649e9998bccba5/metadata_xml/cioos_template.jinja2#L887)) in less platform is not used. In the case of no platform instrument should appear directly under mac:MI_AcquisitionInformation. We are not capturing this case currently in the template.

**Comment by n-a-t-e** [comment]
We are still not capturing this case

**Comment by n-a-t-e** [comment]
As discussed again recently, platform will not be required (though it is strongly suggested if there is a platform). So Instrument could be supplied on it's own or under Platform, or both. The yaml could look like this:

```yaml    
platform:
  name: platform_name

  instruments:
    - id: instrument_on_a_platform

instruments:
  - id: instrument_not_on_a_platform
```
