### ISSUE TITLE
Split keywords into themes

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/metadata-xml#55]
Currently all of our XML keywords, which includes CIOOS EOVs, French translation of EOVs, CF names, place names, etc., are put in a single descriptiveKeywords element in the XML file. However, looking at the HNAP standard, it allows multiple descriptiveKeywords elements, each of which can have any number of keywords sub-elements, as well as a theme that defines each of these separate groupings. An example of this can be found by downloading the HNAP XML file for the following dataset:
https://open.canada.ca/data/en/dataset/a650f132-7502-402f-a42e-7ba4dea3f829
The ISO19115-1 document also defines some newer standard vocabularies that can be used for these themes. This could help during e.g. CKAN harvest, when the use of a common theme for CIOOS EOVs could help parse these more reliably.

**Comment by n-a-t-e** [comment]
I modified an example from the ACDD website to show how we can do this:
`keywords_vocabulary: "CIOOS:CIOOS EOVs, CF:NetCDF COARDS Climate and Forecast Standard Names"`
`keywords:"CF:sea_suface_temperature,CIOOS:subSurfaceCurrents"`
`keywords_fr:"CIOOS:french keyword`

http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_1-3#keywords_vocabulary

Or if we switch to a nested input format, eg in Pygeometa you can do this:

```
    keywords:
        default:
            keywords_en: [kw1 in English, kw2 in English, kw3 in English]
            keywords_fr: [kw1 in French, kw2 in French, kw3 in French]
        wmo:
            keywords_en: [FOO, BAR]
            keywords_type: theme
        gc_cst:
            keywords_en: [kw1, kw2]
            keywords_fr: [kw1, kw2]
```
